[[GAP_pkg_deepthought]]
arch = "aarch64"
git-tree-sha1 = "c36ae4de4cab04bf95bcabdf80de26467bd3ee75"
os = "macos"

    [[GAP_pkg_deepthought.download]]
    sha256 = "9acd907df6aa64213aa0244fcc509a028ef6d8d092031465547cf73c1932b087"
    url = "https://github.com/lgoettgens/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.1000.0+0/GAP_pkg_deepthought.v101.1000.0.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_deepthought]]
arch = "aarch64"
git-tree-sha1 = "41ab934bf4accc5272f7d729e35220d390cd8914"
libc = "glibc"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "2419ff26ad372345716361aec2070c95b0636d15c771ea20f94464cd2a911aac"
    url = "https://github.com/lgoettgens/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.1000.0+0/GAP_pkg_deepthought.v101.1000.0.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_deepthought]]
arch = "aarch64"
git-tree-sha1 = "0f41814eaa58a9bd26bd65d9522291b0ff222c72"
libc = "musl"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "2f2b25022fae2d73958b2e60a7d968083c3d1fbdf819beb00eef52ebacf722b2"
    url = "https://github.com/lgoettgens/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.1000.0+0/GAP_pkg_deepthought.v101.1000.0.aarch64-linux-musl.tar.gz"
[[GAP_pkg_deepthought]]
arch = "aarch64"
git-tree-sha1 = "3e5a27f0186fa0670bcf73bdf5a207231f6b2217"
os = "freebsd"

    [[GAP_pkg_deepthought.download]]
    sha256 = "60104c66c3af395f523563c549ae5a3b1039fcde09037a26ba9730afd66245f8"
    url = "https://github.com/lgoettgens/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.1000.0+0/GAP_pkg_deepthought.v101.1000.0.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_deepthought]]
arch = "powerpc64le"
git-tree-sha1 = "d2447f137acaa2fd13f0d427aecef8264c5954fa"
libc = "glibc"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "a10c16836b4ddc40c29680d7424c0ca95542f6d971e06a3f263d244f4b02ca3b"
    url = "https://github.com/lgoettgens/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.1000.0+0/GAP_pkg_deepthought.v101.1000.0.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_deepthought]]
arch = "riscv64"
git-tree-sha1 = "a6eb7018790d2974fe8c05a261618b745de4061f"
libc = "glibc"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "a0a5c7d92fb1b2cc8ab5425a531fd881415c7a0f40877b12174b29b7df6de237"
    url = "https://github.com/lgoettgens/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.1000.0+0/GAP_pkg_deepthought.v101.1000.0.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_deepthought]]
arch = "x86_64"
git-tree-sha1 = "876453b8af79ffb139c1db6fb10d031c980e4dc0"
os = "macos"

    [[GAP_pkg_deepthought.download]]
    sha256 = "e03961ee6d9d553499715eb99c1d34b64ca1d18fbd5e9c8f5efd27bd852d6452"
    url = "https://github.com/lgoettgens/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.1000.0+0/GAP_pkg_deepthought.v101.1000.0.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_deepthought]]
arch = "x86_64"
git-tree-sha1 = "62d675060a99127d3991f7e6093677394690af36"
libc = "glibc"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "c9658e0f4592b93d5b56b906dab9c99d17e4b9c6d356187b425d7f93af730f93"
    url = "https://github.com/lgoettgens/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.1000.0+0/GAP_pkg_deepthought.v101.1000.0.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_deepthought]]
arch = "x86_64"
git-tree-sha1 = "dda76f0d0aa9a4a9bd0ced3a5ed448a4a880074e"
libc = "musl"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "cd685363a1c4faacb9187a62383ffb6cf00cff62676d607e55fb6302a0557cf1"
    url = "https://github.com/lgoettgens/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.1000.0+0/GAP_pkg_deepthought.v101.1000.0.x86_64-linux-musl.tar.gz"
[[GAP_pkg_deepthought]]
arch = "x86_64"
git-tree-sha1 = "07cca0767a18d29232434402a18397008bfa2581"
os = "freebsd"

    [[GAP_pkg_deepthought.download]]
    sha256 = "3a386e919c9077c500df9c762473c7e7d414716a2f78037ad5f5f0f4d70ddabd"
    url = "https://github.com/lgoettgens/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.1000.0+0/GAP_pkg_deepthought.v101.1000.0.x86_64-unknown-freebsd.tar.gz"
