[[GAP_pkg_deepthought]]
arch = "aarch64"
git-tree-sha1 = "a5360135209ed14e0e4e6e8fd008427749a77b4b"
os = "macos"

    [[GAP_pkg_deepthought.download]]
    sha256 = "5fcf579db5df77b18cdaf7522958b30ea652248c00182dd85a6458c412542190"
    url = "https://github.com/lgoettgens/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.900.1+0/GAP_pkg_deepthought.v101.900.1.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_deepthought]]
arch = "aarch64"
git-tree-sha1 = "20e45b0fab4994e5ca4101f5cc561c4f9745e227"
libc = "glibc"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "f400c999812f3c955540a376f1d5e6671a41e8ef97d0b5f572dec4dfdca637ac"
    url = "https://github.com/lgoettgens/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.900.1+0/GAP_pkg_deepthought.v101.900.1.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_deepthought]]
arch = "aarch64"
git-tree-sha1 = "01f815c1c627c3d860911e43d5e698a74d1b07a8"
libc = "musl"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "d864201de326e95ab18932a0dcd480e2f9f289539e1f60bd1504f68c5e8e096f"
    url = "https://github.com/lgoettgens/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.900.1+0/GAP_pkg_deepthought.v101.900.1.aarch64-linux-musl.tar.gz"
[[GAP_pkg_deepthought]]
arch = "aarch64"
git-tree-sha1 = "e56ef170940911b9d1d13f2e647c0e4a2006b6ec"
os = "freebsd"

    [[GAP_pkg_deepthought.download]]
    sha256 = "5a79b1e6ec545d1ad6cd6835e521dd6eb28d1fd1f1a1a581030da1e18ef36354"
    url = "https://github.com/lgoettgens/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.900.1+0/GAP_pkg_deepthought.v101.900.1.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_deepthought]]
arch = "powerpc64le"
git-tree-sha1 = "52aab002866ecd95bec4707954e10216dc04ad87"
libc = "glibc"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "c0f118c71f564a4a299263e0b36e14718a1dc1bc464a7aaec10b141d59035250"
    url = "https://github.com/lgoettgens/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.900.1+0/GAP_pkg_deepthought.v101.900.1.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_deepthought]]
arch = "riscv64"
git-tree-sha1 = "73f2cca4464ca8ea94902c644663f6d67fee1c7d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "869b4986570db2e63253b5f640e6b23ae89f59d000b00ff804a882ad3ffc1e79"
    url = "https://github.com/lgoettgens/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.900.1+0/GAP_pkg_deepthought.v101.900.1.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_deepthought]]
arch = "x86_64"
git-tree-sha1 = "eac2f561d4dafe9c559f971c22f8ef7a6eb4aeab"
os = "macos"

    [[GAP_pkg_deepthought.download]]
    sha256 = "f16ac18a26022f11c5152148d99aa3b090697eaa5cd4a1d7b6c61f359fc04229"
    url = "https://github.com/lgoettgens/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.900.1+0/GAP_pkg_deepthought.v101.900.1.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_deepthought]]
arch = "x86_64"
git-tree-sha1 = "59a60027f6c7fa2c6f5392aef84c063d2e9ab488"
libc = "glibc"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "e568e854cddab4ff81911f72de67f0515c2e718806897fbc8d46fe9df5575611"
    url = "https://github.com/lgoettgens/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.900.1+0/GAP_pkg_deepthought.v101.900.1.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_deepthought]]
arch = "x86_64"
git-tree-sha1 = "085f3530e3fe28f76583c77c9d8d4b5f493ec541"
libc = "musl"
os = "linux"

    [[GAP_pkg_deepthought.download]]
    sha256 = "65654c9d53b3f233e6aa29463d3f4937dcc7126fe5db3a8d9269128a48a345c2"
    url = "https://github.com/lgoettgens/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.900.1+0/GAP_pkg_deepthought.v101.900.1.x86_64-linux-musl.tar.gz"
[[GAP_pkg_deepthought]]
arch = "x86_64"
git-tree-sha1 = "8644e8e3c1af6ac8967a629e47b24ad6a2f5254c"
os = "freebsd"

    [[GAP_pkg_deepthought.download]]
    sha256 = "966551d2c5821d75effc134efea56b66e1231ddbdac65c987c6136a0a11db261"
    url = "https://github.com/lgoettgens/GAP_pkg_deepthought_jll.jl/releases/download/GAP_pkg_deepthought-v101.900.1+0/GAP_pkg_deepthought.v101.900.1.x86_64-unknown-freebsd.tar.gz"
